# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the project and build
COPY . .
RUN npm run build

# Expose any ports if needed (not specified here)

# Start the server with the GitHub token passed as argument
CMD ["node", "dist/server.js"]
